import{a as c,i as l,C as d}from"./assets/vendor-cee7d47c.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function p(){c.defaults.headers.common["x-api-key"]="live_DkjqTDSOD0uOwcyk5E7MuJms89zGHMAHzGcGyX0DktQBX5FB2DAgH1fKrExnRumo";try{return(await c.get("https://api.thecatapi.com/v1/breeds")).data}catch(r){throw console.log(r),l.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topLeft"}),r}}const u="https://api.thecatapi.com/v1/images/search";async function m(r){const e=`${u}?breed_ids=${r}`;try{return(await c.get(e)).data[0]}catch(n){throw l.settings({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topLeft"}),n}}const s={select:document.getElementById("choices"),loader:document.querySelector(".loader"),error:document.querySelector(".error"),info:document.querySelector(".cat-info")};s.loader.classList.remove("visually-hidden");function f(r){const e=s.select;r.forEach(n=>{const i=new Option(n.name,n.id);e.add(i)}),new d(e,{itemSelectText:""})}p().then(r=>{s.select.classList.remove("visually-hidden"),s.loader.classList.add("visually-hidden"),f(r)}).catch(r=>{s.loader.classList.add("visually-hidden")});s.select.addEventListener("change",h);function h(){s.info.innerHTML="";const r=this.value;s.loader.classList.remove("visually-hidden"),m(r).then(e=>{s.loader.classList.add("visually-hidden"),s.info.innerHTML=`
      <div class="description">
      <div class="cat-info__image-wrapper">
    <img class="cat-info__image" width="400" src="${e.url}" alt="${e.breeds[0].name}" />
    </div>
    <div class="text">
      <p class="cat-info__name">Breed: ${e.breeds[0].name}</p>
      <p class="cat-info__description"><span class="cat-info__title">Description: </span>${e.breeds[0].description}</p>
      <p class="cat-info__temperament"><span class="cat-info__title">Temperament: </span>${e.breeds[0].temperament}</p>
      </div>
      </div>
    `}).catch(e=>{console.error(e),l.error({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",position:"topLeft"})})}
//# sourceMappingURL=commonHelpers.js.map
